version: "3.9"
services:

  broker:
    image: eclipse-mosquitto:2.0.1
    networks:
      - localnet
    ports:
      - "1883:1883"

  node-red:
    depends_on:
      - broker
    image: nodered/node-red:latest-12
    volumes:
      - "./node-red:/data"
    user: "0"
    networks:
      - localnet
    ports:
      - "1880:1880"
  
networks:
  localnet: